### ISSUE TITLE
中文姓名生成效率太低

### ISSUE THREAD

**Issue by seyoatda** [easysoft/zendata#4]
测试了一下生成10条数据花了60秒，是我的写法有问题吗？这效率已经超出我的想象范围了。
yaml文件如下：
```
title: 用户数据生成
fields:
  - field: name
    from: name.cn.given.v1
    where: "double='true'"
    select: name
```
看了一下人名的excel里有几万条数据。
