### ISSUE TITLE
range 不支持浮点数

### ISSUE THREAD

**Issue by Sean-214** [easysoft/zendata#41]
数据格式配置文件
```
title: test_random_float
fields:
  - field: float
    range: 1.0001-1.9999
    postfix: "\t"
  - field: float_r
    range: 1.0001-1.9999:R
```

生成的数据
```
1.0	1.0
1.0	1.0
1.0	1.0
1.0	1.0
1.0	1.0
1.0	1.0
1.0	1.0
1.0	1.0
1.0	1.0
1.0	1.0
```
